### ISSUE TITLE
"ValueError: Rank(A) < p or Rank([P; A; G]) < n" is incorrect

### ISSUE THREAD

**Issue by SimonMossmyr** [cvxopt/cvxopt#135]
In my implementation of SVM Regression I use the `cvxopt.solvers.qp()` function. It throws the error

    ValueError: Rank(A) < p or Rank([P; A; G]) < n

in spite of Rank(A) = p and Rank([P; A; G]) = n.

You can look at my code here: [svm.zip](https://github.com/cvxopt/cvxopt/files/2721462/svm.zip).
As you can see in `main.py:63-66`, the constraint holds true, but `qp()` still throws the error.

Entire error:

    $ python main.py 
    Traceback (most recent call last):
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/misc.py", line 1429, in factor
        lapack.potrf(F['S']) 
    ArithmeticError: 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/coneprog.py", line 2065, in coneqp
        try: f = kktsolver(W)
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/coneprog.py", line 1981, in kktsolver
        return factor(W, P)
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/misc.py", line 1444, in factor
        lapack.potrf(F['S']) 
    ArithmeticError: 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "main.py", line 119, in <module>
        test_sinc()
      File "main.py", line 111, in test_sinc
        a, a_hat, b = solve_SVR(P, q, G, h, A, b, X, y, kernels.linear_spline)
      File "main.py", line 80, in solve_SVR
        solution = qp(P, q, G, h, A, b)
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/coneprog.py", line 4487, in qp
        return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
      File "/home/moss/anaconda3/lib/python3.6/site-packages/cvxopt/coneprog.py", line 2067, in coneqp
        raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
    ValueError: Rank(A) < p or Rank([P; A; G]) < n

**Comment by ShubhankarKapoor** [comment]
Hi,

I have the same issue, i checked the rank condition and both the cases are satisfied. I was wondering if rank is the problem or there could be any other potential issue.

Thanks

**Comment by martinandersen** [comment]
It could be because your problem is ill-conditioned: the Newton system may be singular even if Numpy determines that the rank conditions are satisfied. Try to check the condition number of A and/or [P; A; G].

**Comment by ShubhankarKapoor** [comment]
Hi,

Thanks for the reply I checked the condition number, and I tried 3 different cases (slightly different values)
Case 1: Condition Number of A = 7.07 Condition Number of [P;A;G] = 3.78
Case 2: Condition Number of A = 7.07 Condition Number of [P;A;G] = 35.46
Case 3: Condition Number of A = 7.07 Condition Number of [P;A;G] = 50.86

And the rank is the same in all the 3 cases.
So the qp solver works for case 1 and case 3 but not for case 2. Any recommendations will be appreciated.

Thanks

**Comment by vqwerty03** [comment]
Having exactly the same issue as reported above. 

Traceback (most recent call last):
  File "...\python_cvxpy\Lib\site-packages\cvxopt\misc.py", line 1429, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\python_cvxpy\Lib\site-packages\cvxopt\coneprog.py", line 680, in conelp
    try: f = kktsolver(W)
  File "...\python_cvxpy\Lib\site-packages\cvxopt\coneprog.py", line 585, in kktsolver
    return factor(W)
  File "...\python_cvxpy\Lib\site-packages\cvxopt\misc.py", line 1444, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/str/RV/vol.py", line 1187, in <module>
    main()
  File "H:/str/RV/vol.py", line 1180, in main
    rv.cvx_optimize()
  File "H:/str/RV/vol.py", line 1012, in cvx_optimize
    sol = solvers.lp(cvec_m, G_m, b_m)
  File "...\python_cvxpy\Lib\site-packages\cvxopt\coneprog.py", line 3010, in lp
    dualstart, kktsolver = kktsolver, options = options)
  File "...\python_cvxpy\Lib\site-packages\cvxopt\coneprog.py", line 682, in conelp
    raise ValueError("Rank(A) < p or Rank([G; A]) < n")
ValueError: Rank(A) < p or Rank([G; A]) < n

Any thoughts appreciated. Thanks!

**Comment by martinandersen** [comment]
Which version of CVXOPT are you using? How did you install it?

**Comment by martin-91x** [comment]
Hi, I'm currently having the same problems depending on the input values.

In my case, I'm changing the values of P, keeping everything else the same.
I've checked the rank of every matrix but they are correct and do not change from a working to a failing case.

I've also checked the condition numbers as suggested above:
Working: P: 5.66e33, G: 1.0, A: 1.0, [P; A; G]: 455.73
Failing: P: 2.27e33, G: 1.0, A: 1.0, [P; A; G]: 73.77

Regarding the version: I've simply used pip to install and I'm running version 1.2.5.post1

**Comment by martinandersen** [comment]
What's the condition number of P + G.T*G? My guess is that it is large.

You could also try to use a different KKT solver (e.g., `kktsolver="chol"`; the default for `qp()` is `kktsolver="chol2"`).

**Comment by martin-91x** [comment]
Hi,

some condition numbers for P + G.T*G are:
- Working examples: 70.68, 102.09, 734.35, 456.51 (working case from above)
- Failing: 73.5 (failing case from above), 16.1, 824.3

Changing the KKT solver gives the same result.

**Comment by martinandersen** [comment]
Perhaps it is a scaling issue. Do you have a small example?
