### ISSUE TITLE
Error when using cvxopt with MOSEK 9

### ISSUE THREAD

**Issue by bderrett** [cvxopt/cvxopt#144]
When I try to solve a QP using cvxopt-1.2.3 using MOSEK 9.0.95 I get the error:

`Traceback (most recent call last):
  File "run.py", line 6, in <module>
    print(cvxopt.solvers.qp(P=cvxopt.matrix([[1.]]), q=cvxopt.matrix([1.]), G=cvxopt.matrix([[1.]]), h=cvxopt.matrix([[-1.]]), solver='mosek'))
  File "../site-packages/cvxopt/coneprog.py", line 4368, in qp
    if solsta in (mosek.solsta.optimal, mosek.solsta.near_optimal):
AttributeError: type object 'solsta' has no attribute 'near_optimal'`

The [MOSEK 9 release notes](https://docs.mosek.com/9.0/pythonapi/changes.html) mention the removal of the 'near_optimal' attribute:

> Removed all Near problem and solution statuses i.e. solsta.near_optimal, solsta.near_prim_infeas_cer, etc. See Sec. 13.3.3 (Adjusting optimality criteria).

Please may someone make a change in cvxopt to handle this? Many thanks.

**Comment by martinandersen** [comment]
Thanks for reporting this—we will address it in the next release.

**Comment by kirelagin** [comment]
This issue seems to still be relevant (but I don’t have the “reopen” button, hence just a comment, /cc @martinandersen).

Out of the three changes in the commit, [the second one](https://github.com/cvxopt/cvxopt/commit/22f5343e329a1d6316d2d2b22d6e40cd47df863d#diff-2f3bfb0f4ea1271af391cf801016f5d20541b90fc426afd2d561f60c28c6a584R3353) does not actually do anything, and thus `socp` will still fail.
