### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by antoinecomp** [cvxopt/cvxopt#171]
After installing cvxopt I can't import it properly. Indeed it seems that some dll module could not be found:

```
C:\Users\antoi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python3.7.exe C:/Users/antoi/Documents/Programming/ModeloMarkowitz/modeloMarkowitz.py
Traceback (most recent call last):
  File "C:/Users/antoi/Documents/Programming/ModeloMarkowitz/modeloMarkowitz.py", line 4, in <module>
    import cvxopt as opt
  File "C:\Users\antoi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxopt\__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: DLL load failed: The specified module could not be found.
```

What did I missed? What can I do?

I'm using python3.7, anaconda3 ...

**Comment by martinandersen** [comment]
Try installing cvxopt from the conda-forge channel:

```
conda install -c conda-forge cvxopt
```
