### ISSUE TITLE
Miniconda's 'conda build' defaults to outdated anaconda/cvxopt instead of conda-forge/cvxopt.

### ISSUE THREAD

**Issue by Viech** [cvxopt/cvxopt#183]
_I accidentially posted this issue before I fully investigated my problem so I'm not yet sure if this is really an issue on your end or just something about my setup. I'll give an update when I find a solution. Sorry!_

I have a `meta.yaml` with the following requirements for a conda build of mine:
```
requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - cvxopt
    - numpy
```

Building for Python 3.9 gives me the following error:
```
Traceback (most recent call last):
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/resolve.py", line 1322, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
cvxopt -> mkl-service[version='>=2,<3.0a0'] -> python[version='>=3.9,<3.10.0a0']
python[version='>=3.9,<3.10.0a0']
cvxopt -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
numpy -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Package tzdata conflicts for:
python[version='>=3.9,<3.10.0a0'] -> tzdata
numpy -> python[version='>=3.9,<3.10.0a0'] -> tzdata

Package numpy conflicts for:
numpy
cvxopt -> mkl-service[version='>=2,<3.0a0'] -> numpy[version='>=1.11.3,<2.0a0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/…/.conda/envs/picos-build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/build.py", line 3008, in build_tree
    packages_from_this = build(metadata, stats,
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/build.py", line 2048, in build
    create_build_envs(top_level_pkg, notest)
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/build.py", line 1926, in create_build_envs
    raise e
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/build.py", line 1905, in create_build_envs
    environ.get_install_actions(m.config.test_prefix,
  File "/…/.conda/envs/picos-build/lib/python3.8/site-packages/conda_build/environ.py", line 804, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"numpy[version='>=1.11.3,<2.0a0']", "python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']", "python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']", "python[version='>=3.9,<3.10.0a0']", 'tzdata'}
```

It seems that the default repository used by `conda build` provided by miniconda3 4.8.3 is `anaconda/cvxopt` which only has CVXOPT 1.2.0 while `conda-forge/cvxopt` provides 1.2.5 with Python 3.9 support.

**Comment by martinandersen** [comment]
You probably have to specify the conda-forge channel when building; see https://docs.conda.io/projects/conda-build/en/latest/concepts/channels.html

**Comment by Viech** [comment]
Thank you, this works. I should also require `cvxopt >1.2.0` in `meta.yaml` to be on the safe side.

Would it make sense to have the `anaconda/cvxopt` package removed so that users don't install an outdated version? Otherwise this issue can probably be closed.

**Comment by martinandersen** [comment]
Yes, I think it makes sense, but the anaconda/cvxopt package is not maintained by us, so I’ll close this issue.
