### ISSUE TITLE
ValueError: domain error

### ISSUE THREAD

**Issue by leovam** [cvxopt/cvxopt#202]
Hi, 

I am using `cvxpot` to solver a QP problem, and encounter a domain error, I looked at posts with similar issue and tried the solutions there but the error still there, here is the Error output:

```
Traceback (most recent call last):

  File "C:\Users\Leo\AppData\Local\Temp/ipykernel_27580/4196143146.py", line 1, in <module>
    F_infer = _quad_prog_BCmu2F(B, C_init)

  File "F:\Projects\RNAdeconv\deconvRNAsc\haoyunl\rna_deconv_test.py", line 88, in _quad_prog_BCmu2F
    fj = _cvxopt_solve_qp(P, q, G, h, A, b)

  File "F:\Projects\RNAdeconv\deconvRNAsc\haoyunl\rna_deconv_test.py", line 41, in _cvxopt_solve_qp
    sol = cvxopt.solvers.qp(*args)

  File "d:\anaconda3\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)

  File "d:\anaconda3\lib\site-packages\cvxopt\coneprog.py", line 2243, in coneqp
    if iters == 0:  W = misc.compute_scaling(s, z, lmbda, dims)

  File "d:\anaconda3\lib\site-packages\cvxopt\misc.py", line 285, in compute_scaling
    W['d'] = base.sqrt( base.div( s[mnl:mnl+m], z[mnl:mnl+m] ))

ValueError: domain error
```

Any idea about what might be wrong and how to fix it? Thanks!

**Comment by stephane-caron** [comment]
I'm running into a similar problem https://github.com/cvxopt/cvxopt/issues/229 although the traceback is not exactly the same.

You could try setting ``cvxopt.solvers.options["show_progress"] = True`` to see if the iterates also yield NaNs into your problematic case.

**Comment by mvds314** [comment]
I'm having the same problem, downgrading to version 1.2.7 (in Python 3.9) worked for me as a temporary solution.
