### ISSUE TITLE
Incompatible cvxopt.base for Apple arm64 

### ISSUE THREAD

**Issue by sunilshah** [cvxopt/cvxopt#227]
I upgraded to Mac OS 13.0.   I am running Python 3.10.8 under homebrew in native (arm64) mode.

I re-installed cvxopt 1.3.0 after upgrading to Mac OS 13.0 

Upon importing cvxopt I get the following error.

```
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/cvxopt/__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (no such file), '/opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
 >>> exit()

% arch          
arm64

% file /opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so
/opt/homebrew/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so: Mach-O 64-bit bundle x86_64


````
It appears that the Universal bundle has x86_64 dynamic library.

**Comment by kryft** [comment]
It's been a few months, but I think I had the same issue, and the problem was that the universal2 wheel for cvxopt is broken: as I understand it, a universal2 wheel is by definition supposed to support both arm64 and x86_64, so pip will try to install it on an arm64 machine, but the cvxopt wheel only supports x86_64. My workaround is to force pip (or poetry) to install cvxopt from source.

**Comment by sunilshah** [comment]
I have been unable to install from source for a while as well.   See issue on installation on M1.  #214.
Even when it builds from source, run-time errors occur.

**Comment by hashstat** [comment]
I ran into the same issue helping a coworker setup his new M1 mac. The universal wheels on pypi.org aren't universal; they are x86_64 only.

I was able to successfully build a universal wheel using the following command:

`env CFLAGS="-arch arm64 -arch x86_64" python setup.py bdist_wheel --plat-name macosx_12.0_universal2`

The resulting wheel is almost twice as large as the single-arch build, which is expected. Also, running `lipo -archs ...` on the resulting extensions produces `x86_64 arm64` instead of just `x86_64`.

**Comment by sunilshah** [comment]
@hashstat 

I am no longer running Monterey but now running on Mac OS Ventura 13.0.1.  So, how would the command be different?  

Can you also please post  a complete set of commands you used to install from source?  If the commands are different Mac OS 13.0.1 can you please post the updated command?

Thanks

**Comment by sunilshah** [comment]
@hashstat 

It worked with the first option.    

For completeness, here is the log.   

```
env CFLAGS="-arch arm64 -arch x86_64" pip3 wheel --no-deps --no-binary cvxopt --build-option --plat-name --build-option macosx_13_0_universal2 cvxopt==1.3.0
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting cvxopt==1.3.0
  Using cached cvxopt-1.3.0.tar.gz (4.1 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: cvxopt
  Building wheel for cvxopt (setup.py) ... done
  Created wheel for cvxopt: filename=cvxopt-1.3.0-cp310-cp310-macosx_13_0_universal2.whl size=554884 sha256=feeb1d69ed7f87261bbe7f447a8676123cb4918a30b340d6046c094afd976713
  Stored in directory: /Users/sunilshah/Library/Caches/pip/wheels/b0/a0/f4/7c708f43555fdbd678d006505c6fb9a9a91add50a083838820
Successfully built cvxopt


 python3                                                                
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvxopt import glpk
>>> exit()
% python3
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
>>> exit()

```  

Build and install did not work. 

```
env CFLAGS="-arch arm64 -arch x86_64" pip3 install --no-binary cvxopt --build-option --plat-name --build-option macosx_13_0_universal2 cvxopt==1.3.0

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --build-option


```

**Comment by hashstat** [comment]
I realized this morning that my build was incomplete using the previously provided commands. *glpk* (and other) modules weren't being built without setting `CVXOPT_BUILD_XXX=1` options, where XXX can be GSL, FFTW, GLPK, or DSDP.

So, for future reference, here is the command to build a complete, portable macOS wheel from source, assuming the *wheel* package is installed, as well as all the required libraries:

`env CFLAGS='-arch arm64 -arch x86_64 -mmacosx-version-min=10.9' CVXOPT_BUILD_{GSL,FFTW,GLPK,DSDP}=1 python setup.py bdist_wheel --plat-name macosx_10_9_universal2`

Or to build that same wheel with pip:

`env CFLAGS='-arch arm64 -arch x86_64 -mmacosx-version-min=10.9' CVXOPT_BUILD_{GSL,FFTW,GLPK,DSDP}=1 pip wheel --no-deps --no-binary :all: --build-option --plat-name --build-option macosx_10_9_universal2 cvxopt==1.3.0`

And to build and install for arm64e, there is no need for the universal build bits:

`env CFLAGS='-arch arm64' CVXOPT_BUILD_{GSL,FFTW,GLPK,DSDP}=1 pip install --no-binary cvxopt cvxopt==1.3.0`

On arm64e hardware, I also had to add some additional flags to the **CFLAGS** environment variable: `-I/opt/homebrew/include -L/opt/homebrew/lib`.

Hope this helps anyone else struggling to get cvxopt to work on the new Apple hardware. And I would encourage the developers to build and upload a *true* universal2 wheel.

**Comment by matteoacrossi** [comment]
I was able to build my wheels with my command above. But is there any plan to fix this so that `pip install cvxopt` will work on `arm64`?
