### ISSUE TITLE
Iterates become NaN on unfeasible sparse problem

### ISSUE THREAD

**Issue by stephane-caron** [cvxopt/cvxopt#229]
I'm running into a ValueError exception with a traceback similar to (but not exactly the same as) https://github.com/cvxopt/cvxopt/issues/202.

Here is a reproducible example:

* Decompress the file ``QP.mat`` from this archive: [QP.zip](https://github.com/cvxopt/cvxopt/files/9921444/QP.zip)
* Run this code:
```python
import cvxopt
import numpy as np
import scipy.io as spio
import scipy.sparse as spa

def spmatrix_from_csc(M):
    coo = M.tocoo()
    return cvxopt.spmatrix(
        coo.data.tolist(), coo.row.tolist(), coo.col.tolist(), size=M.shape
    )

def concatenate_box_bound(G, h, b, sign):
    G = spa.vstack([G, sign * spa.eye(len(b))], format="csc")
    h = np.concatenate((h, sign * b))
    return (G, h)

m = spio.loadmat("QP.mat", squeeze_me=True)
P = m["P"].astype(float).tocsc()
q = m["q"].astype(float)
G = m["G"].astype(float).tocsc()
h = m["h"].astype(float)
lb = m["lb"].astype(float)
ub = m["ub"].astype(float)

G, h = concatenate_box_bound(G, h, lb, -1.0)
G, h = concatenate_box_bound(G, h, ub, +1.0)

cvxopt.solvers.qp(
    spmatrix_from_csc(P),
    cvxopt.matrix(q),
    spmatrix_from_csc(G),
    cvxopt.matrix(h),
)
```

The output on my machine is:

```console
$ python reprod.py                                 ✔  36s 
     pcost       dcost       gap    pres   dres
 0: -6.9100e+01  3.4474e+01  2e+03  1e+00  2e+00
 1: -2.9284e+01  7.3567e+01  3e+02  3e-01  4e-01
 2: -2.7029e+01  5.4319e+02  1e+02  2e-01  3e-01
 3: -2.7198e+01  2.9981e+03  2e+02  2e-01  3e-01
 4: -2.7061e+01  3.0647e+04  1e+03  2e-01  2e-01
 5: -2.6774e+01  9.2343e+05  5e+03  2e-01  2e-01
 6: -2.6695e+01  1.5580e+08  7e+04  2e-01  2e-01
 7: -2.6688e+01  3.3538e+11  2e+06  2e-01  2e-01
 8: -2.6688e+01  4.5254e+16  3e+09  2e-01  3e-01
 9: -2.6688e+01  5.9877e+23  4e+14  2e-01  2e+06
10: -2.6688e+01  7.9223e+32  6e+21  2e-01  2e+15
11: -2.6688e+01  7.8699e+43  2e+32  2e-01  3e+26
12: -2.6688e+01  4.0400e+55  1e+42  2e-01  1e+38
13: -2.6688e+01  1.0440e+69  6e+54  2e-01  3e+51
14: -2.6688e+01  5.7822e+81  3e+67  2e-01  2e+64
15: -2.6688e+01  5.3056e+92  3e+78  2e-01  1e+75
16: -2.6688e+01  7.5116e+106  1e+92  2e-01  2e+89
17: -2.6688e+01  2.4188e+121  2e+106  2e-01 1e+104
18: -2.6688e+01  1.3574e+136  1e+120  2e-01 2e+119
19: -2.6688e+01  1.9871e+152  2e+136  2e-01 8e+135
20: -2.6688e+01  1.5337e+167  1e+151  2e-01 3e+150
21: -2.6688e+01  5.9563e+181  3e+165  2e-01    inf
22: -2.6688e+01  1.6182e+198  6e+181  2e-01    inf
23: -2.6688e+01  1.6318e+212  6e+195  2e-01    inf
24: -2.6688e+01  4.3198e+227  2e+211  2e-01    inf
25: -2.6688e+01  2.1012e+238  8e+221  4e-01    inf
26: -2.6688e+01  4.2793e+247  2e+231  4e-01    inf
27: -2.6688e+01  1.7113e+253  6e+236  4e-01    inf
28: -2.6688e+01  2.3281e+255  8e+238  4e-01    inf
29: -2.6688e+01  1.0724e+256  4e+239  4e-01    inf
30: -2.6688e+01  4.2000e+256  1e+240  4e-01    inf
31: -2.6688e+01  1.6654e+257  6e+240  4e-01    inf
32: -2.6688e+01  7.0945e+257  2e+241  4e-01    inf
33: -2.6688e+01  3.3555e+258  1e+242  4e-01    inf
34: -2.6688e+01  1.8025e+259  6e+242  4e-01    inf
35: -2.6688e+01  1.1147e+260  3e+243  4e-01    inf
36: -2.6688e+01  7.9556e+260  2e+244  4e-01    inf
37: -2.6688e+01  6.4905e+261  2e+245  4e-01    inf
38: -2.6688e+01  5.9379e+262  2e+246  4e-01    inf
39: -2.6688e+01  5.9475e+263  2e+247  4e-01    inf
40: -2.6688e+01  6.3699e+264  2e+248  4e-01    inf
41: -2.6688e+01  7.1504e+265  2e+249  4e-01    inf
42: -2.6688e+01  8.2851e+266  2e+250  4e-01    inf
43: -2.6688e+01  9.8020e+267  3e+251  4e-01    inf
44: -2.6688e+01  1.1754e+269  3e+252  4e-01    inf
45: -2.6688e+01  1.4215e+270  4e+253  4e-01    inf
46: -2.6688e+01  1.7287e+271  5e+254  4e-01    inf
47: -2.6688e+01  2.1094e+272  6e+255  4e-01    inf
48: -2.6688e+01  2.5794e+273  7e+256  4e-01    inf
49: -2.6688e+01  3.1585e+274  9e+257  4e-01    inf
50: -2.6688e+01  3.8709e+275  1e+259  4e-01    inf
51:      nan      nan  nan  0e+00    nan
Traceback (most recent call last):
  File "reprod.py", line 31, in <module>
    cvxopt.solvers.qp(
  File "/home/frankd/.local/lib/python3.8/site-packages/cvxopt/coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "/home/frankd/.local/lib/python3.8/site-packages/cvxopt/coneprog.py", line 2519, in coneqp
    misc.update_scaling(W, lmbda, ds, dz)
  File "/home/frankd/.local/lib/python3.8/site-packages/cvxopt/misc.py", line 450, in update_scaling
    s[:m] = base.sqrt( s[:m] )
ValueError: domain error
```

**Comment by martinandersen** [comment]
The [qp](https://cvxopt.org/userguide/coneprog.html#quadratic-programming) routine is an interface to [coneqp](https://cvxopt.org/userguide/coneprog.html#quadratic-cone-programs), which requires that the problem is solvable. The problem instance is primal infeasible. 

The qp interface generates certificates of infeasibility if you select MOSEK as the solver (`solver='MOSEK'`), and so does [conelp](https://cvxopt.org/userguide/coneprog.html#linear-cone-programs), but this requires you to reformulate the QP as a cone LP.
