### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by tht18** [cvxopt/cvxopt#241]
Hello,
I've been tried installing CVXOPT without success.

1. Using pip install: the installation seems to run successfully, but importing the package raises error:
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import cvxopt

File ~\AppData\Roaming\Python\Python39\site-packages\cvxopt\__init__.py:57, in <module>
     54     if os.path.isdir(extra_dll_dir):  
     55         os.add_dll_directory(extra_dll_dir)
---> 57 import cvxopt.base
     59 def copyright():
     60     print(__copyright__)

ImportError: DLL load failed while importing base: The specified module could not be found.

2. Downloaded the zip file of latest version 1.3.1, ran the setup.py and encountered the following error:
python setup.py install
Traceback (most recent call last):
  File "C:\Users\TTA\Downloads\cvxopt-1.3.1\setup.py", line 258, in <module>
    setup (name = 'cvxopt',
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 486, in __init__
    _Distribution.__init__(
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
    self.finalize_options()
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 925, in finalize_options
    ep(self)
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools_scm\integration.py", line 104, in infer_version
    _assign_version(dist, config)
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools_scm\integration.py", line 51, in _assign_version
    _version_missing(config)
  File "C:\Users\TTA\AppData\Roaming\Python\Python39\site-packages\setuptools_scm\__init__.py", line 106, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for C:\Users\TTA\Downloads\cvxopt-1.3.1.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

-----
My python version is : 

Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Appreciate any advice or suggestion to get the package installed.
Thanks!

**Comment by martinandersen** [comment]
Have you tried installing from conda-forge?

```
conda install -c conda-forge cvxopt 
```

**Comment by tht18** [comment]
That actually helps once I created a virtual environment and and installed everything afresh.
Thanks for your help!
