### ISSUE TITLE
Import error on El Capitan

### ISSUE THREAD

**Issue by pgkirsch** [cvxopt/cvxopt#45]
Upgraded to El Capitan and now I am getting an import error with cvxopt. This problem persists after reinstalling anaconda and cvxopt.

```
In [1]: import cvxopt
/Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/base.py:3: UserWarning: Module cvxopt was already imported from /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc, but /Users/philippekirschen/cvxopt-1.1.8 is being added to sys.path
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-14abf1b564a4> in <module>()
----> 1 import cvxopt

/Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc in <module>()
    253     exp, log
    254 
--> 255 from cvxopt import solvers, blas, lapack
    256 
    257 __all__ = [ 'blas', 'lapack', 'amd', 'umfpack', 'cholmod', 'solvers',

build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py in <module>()

build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py in __bootstrap__()

ImportError: dlopen(/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so, 2): Symbol not found: _dgesv_
  Referenced from: /Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
```

The same issue seems to have appeared for users of cvxpy (https://groups.google.com/forum/#!topic/cvxpy/7KXcBnunR_Y)

**Comment by martinandersen** [comment]
Is this only an issue with anaconda or also the built-in version of python?

**Comment by pgkirsch** [comment]
It appears to only be an issue with anaconda

**Comment by martinandersen** [comment]
It appears to be a linking problem. Do you compile/install CVXOPT manually or using pip?

**Comment by pgkirsch** [comment]
I installed cvxopt manually

**Comment by martinandersen** [comment]
I just tried installing CVXOPT 1.1.8 (Anaconda / El Capitan) but everything seems to work. Could you try importing cvxopt after starting python with the -v flag to trace import statement?

**Comment by pgkirsch** [comment]
Apologies for the slow response. Did as requested, and it seems like all libraries were being loaded from the correct place (as far as I can tell). I also tried uninstalling and reinstalling again, both manually and using pip, but no luck. Here is the verbose output in case it helps:

```
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/zlib.so", 2);
import zlib # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/zlib.so
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.pyc has bad mtime
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/__future__.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/__future__.py
import __future__ # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/__future__.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/io.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/io.py
import io # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/io.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_io.so", 2);
import _io # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_io.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/time.so", 2);
import time # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/time.so
# /Users/philippekirschen/anaconda/lib/python2.7/zipfile.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/zipfile.py
import zipfile # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/zipfile.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/struct.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/struct.py
import struct # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/struct.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_struct.so", 2);
import _struct # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_struct.so
# /Users/philippekirschen/anaconda/lib/python2.7/shutil.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/shutil.py
import shutil # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/shutil.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/fnmatch.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/fnmatch.py
import fnmatch # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/fnmatch.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/collections.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/collections.py
import collections # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/collections.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_collections.so", 2);
import _collections # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_collections.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/operator.so", 2);
import operator # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/operator.so
# /Users/philippekirschen/anaconda/lib/python2.7/keyword.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/keyword.py
import keyword # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/keyword.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/heapq.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/heapq.py
import heapq # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/heapq.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/itertools.so", 2);
import itertools # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/itertools.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_heapq.so", 2);
import _heapq # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_heapq.so
import thread # builtin
import pwd # builtin
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/grp.so", 2);
import grp # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/grp.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/binascii.so", 2);
import binascii # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/binascii.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/cStringIO.so", 2);
import cStringIO # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/cStringIO.so
# /Users/philippekirschen/anaconda/lib/python2.7/string.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/string.py
import string # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/string.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/strop.so", 2);
import strop # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/strop.so
# /Users/philippekirschen/anaconda/lib/python2.7/functools.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/functools.py
import functools # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/functools.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_functools.so", 2);
import _functools # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_functools.so
# /Users/philippekirschen/anaconda/lib/python2.7/pkgutil.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/pkgutil.py
import pkgutil # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/pkgutil.pyc
import imp # builtin
# /Users/philippekirschen/anaconda/lib/python2.7/token.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/token.py
import token # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/token.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/symbol.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/symbol.py
import symbol # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/symbol.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/platform.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/platform.py
import platform # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/platform.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/plistlib.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/plistlib.py
import plistlib # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/plistlib.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/datetime.so", 2);
import datetime # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/datetime.so
import email # directory /Users/philippekirschen/anaconda/lib/python2.7/email
# /Users/philippekirschen/anaconda/lib/python2.7/email/__init__.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/__init__.py
import email # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/__init__.pyc
import email.mime # directory /Users/philippekirschen/anaconda/lib/python2.7/email/mime
# /Users/philippekirschen/anaconda/lib/python2.7/email/mime/__init__.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/mime/__init__.py
import email.mime # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/mime/__init__.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/parser.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/parser.py
import email.parser # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/parser.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/feedparser.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/feedparser.py
import email.feedparser # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/feedparser.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/errors.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/errors.py
import email.errors # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/errors.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/message.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/message.py
import email.message # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/message.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/uu.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/uu.py
import uu # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/uu.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/charset.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/charset.py
import email.charset # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/charset.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/base64mime.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/base64mime.py
import email.base64mime # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/base64mime.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/utils.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/utils.py
import email.utils # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/utils.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/base64.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/base64.py
import base64 # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/base64.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/random.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/random.py
import random # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/random.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/math.so", 2);
import math # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/math.so
# /Users/philippekirschen/anaconda/lib/python2.7/hashlib.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/hashlib.py
import hashlib # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/hashlib.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_hashlib.so", 2);
import _hashlib # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_hashlib.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_random.so", 2);
import _random # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_random.so
# /Users/philippekirschen/anaconda/lib/python2.7/socket.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/socket.py
import socket # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/socket.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_socket.so", 2);
import _socket # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_socket.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_ssl.so", 2);
import _ssl # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_ssl.so
# /Users/philippekirschen/anaconda/lib/python2.7/urllib.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/urllib.py
import urllib # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/urllib.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/urlparse.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/urlparse.py
import urlparse # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/urlparse.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/ssl.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/ssl.py
import ssl # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/ssl.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/textwrap.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/textwrap.py
import textwrap # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/textwrap.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/contextlib.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/contextlib.py
import contextlib # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/contextlib.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_scproxy.so", 2);
import _scproxy # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/_scproxy.so
# /Users/philippekirschen/anaconda/lib/python2.7/email/_parseaddr.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/_parseaddr.py
import email._parseaddr # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/_parseaddr.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/calendar.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/calendar.py
import calendar # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/calendar.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/locale.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/locale.py
import locale # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/locale.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/quopri.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/quopri.py
import quopri # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/quopri.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/encoders.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/encoders.py
import email.encoders # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/encoders.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/quoprimime.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/quoprimime.py
import email.quoprimime # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/quoprimime.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/email/iterators.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/email/iterators.py
import email.iterators # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/email/iterators.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/tempfile.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/tempfile.py
import tempfile # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/tempfile.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/fcntl.so", 2);
import fcntl # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/fcntl.so
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/parser.so", 2);
import parser # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/parser.so
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/__init__.pyc has bad mtime
# zipimport: zlib available
import pkg_resources._vendor # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/__init__.py
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/__init__.pyc has bad mtime
# zipimport: zlib available
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/__about__.pyc has bad mtime
# zipimport: zlib available
import pkg_resources._vendor.packaging.__about__ # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/__about__.py
import pkg_resources._vendor.packaging # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/__init__.py
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/version.pyc has bad mtime
# zipimport: zlib available
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/_structures.pyc has bad mtime
# zipimport: zlib available
import pkg_resources._vendor.packaging._structures # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/_structures.py
import pkg_resources._vendor.packaging.version # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/version.py
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/specifiers.pyc has bad mtime
# zipimport: zlib available
# zipimport: zlib available
# /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/_compat.pyc has bad mtime
# zipimport: zlib available
import pkg_resources._vendor.packaging._compat # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/_compat.py
import pkg_resources._vendor.packaging.specifiers # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/_vendor/packaging/specifiers.py
import xml # directory /Users/philippekirschen/anaconda/lib/python2.7/xml
# /Users/philippekirschen/anaconda/lib/python2.7/xml/__init__.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/xml/__init__.py
import xml # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/xml/__init__.pyc
import xml.parsers # directory /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers
# /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/__init__.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/__init__.py
import xml.parsers # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/__init__.pyc
# /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/expat.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/expat.py
import xml.parsers.expat # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/xml/parsers/expat.pyc
dlopen("/Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/pyexpat.so", 2);
import pyexpat # dynamically loaded from /Users/philippekirschen/anaconda/lib/python2.7/lib-dynload/pyexpat.so
# /Users/philippekirschen/anaconda/lib/python2.7/encodings/ascii.pyc matches /Users/philippekirschen/anaconda/lib/python2.7/encodings/ascii.py
import encodings.ascii # precompiled from /Users/philippekirschen/anaconda/lib/python2.7/encodings/ascii.pyc
/Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/base.py:3: UserWarning: Module cvxopt was already imported from /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc, but /Users/philippekirschen/cvxopt-1.1.8 is being added to sys.path
import pkg_resources # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
dlopen("/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/base.so", 2);
import cvxopt.base # dynamically loaded from /Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/base.so
import cvxopt.base # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/base.pyc
# zipimport: zlib available
import cvxopt.printing # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/printing.pyc
# zipimport: zlib available
# zipimport: zlib available
import cvxopt.cvxprog # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/cvxprog.pyc
# zipimport: zlib available
import cvxopt.coneprog # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/coneprog.pyc
import cvxopt.solvers # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/solvers.pyc
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
dlopen("/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/blas.so", 2);
import cvxopt.blas # dynamically loaded from /Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/blas.so
import cvxopt.blas # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/blas.pyc
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
# zipimport: zlib available
dlopen("/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so", 2);
import cvxopt.lapack # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/lapack.pyc
import cvxopt # loaded from Zip /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/__init__.py", line 255, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py", line 7, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so, 2): Symbol not found: _dgesv_
  Referenced from: /Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
```

**Comment by martinandersen** [comment]
It looks like you have several CVXOPT installations/directories:

```
/Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/base.py:3: UserWarning: Module cvxopt was already imported from /Users/philippekirschen/anaconda/lib/python2.7/site-packages/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc, but /Users/philippekirschen/cvxopt-1.1.8 is being added to sys.path
/Users/philippekirschen/.python-eggs/cvxopt-1.1.8-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/blas.so
```

On my system, the CVXOPT binaries used by anaconda reside in `~/anaconda/lib/python2.7/site-packages/cvxopt`.

Perhaps you could try to delete all CVXOPT files and then reinstall?

```
rm -rf ~/.python-eggs/cvxopt*
rm -rf ~/cvxopt-1.1.8
rm -rf ~/anaconda/lib/python2.7/site-packages/cvxopt*
```

**Comment by pgkirsch** [comment]
Hmm I noticed that `.python-eggs/cvxopt...` directory and had actually tried that already, with no success. It sounds like this is something specific to my system, so I will continue trying to debug and post a solution here if/when I find it. Thanks for your help!

**Comment by mcg1969** [comment]
I think we know why this problem is occurring. Apple decided to perform some cleanup in `libBLAS.dylib` by removing some symbols that were duplicates of those found in `libLAPACK.dylib`. Unfortunately, if you compile against the assumption those duplicates are there... you break. At least one person out there on the Internets is recommending replacing El Cap's `libBLAS.dylib` with Yosemite's. This is easier said than done thanks to El Cap's System Integrity Protection.

**Comment by pgkirsch** [comment]
Thanks for the info and for following up on this. I've read the instructions for changing libBLAS.dylib, and while it doesn't seem overly complicated, I think I'm going to err on the side of caution, and wait for a less risky solution.

Could you clarify what you mean by "compile against the assumption those duplicates are there"? Is there something that can be changed about the compiling process to resolve the issue?

In the long run do you foresee this issue being resolved by Apple or users or cvxopt?

**Comment by mcg1969** [comment]
I don't see Apple resolving this, no. It's going to have to be resolved by CVXOPT. But it's important to note that it will only affect code that is linked against Apple's BLAS. The specific version of CVXOPT you grabbed, which I actually compiled, did this. I'm pretty sure the standard Anaconda package (1.1.7) and the PIP packages are linked against ATLAS, and that will not be a problem.

**Comment by pgkirsch** [comment]
I just discovered that using cvxopt through my system installation of python (/usr/bin/python) works. Is this what you would have expected @mcg1969?

**Comment by martinandersen** [comment]
I'm not sure that I understand what we need to change in CVXOPT to resolve this problem. When I compile and install CVXOPT on El Capitan (using pip or from the source), it is linked against Apple's BLAS, and everything seems to work. Is it only an issue with Anaconda?

**Comment by mcg1969** [comment]
@pgkirsch: it depends on *exactly* which version of CVXOPT you're using.

@martinandersen: ah yes, of course, recompilation fixes the problem. In fact, if you recompile on El Capitan, _but use an older SDK_, you might find that the package works fine on Yosemite and older.

**Comment by pgkirsch** [comment]
Both 1.1.7 and 1.1.8 work with system python.

**Comment by mcg1969** [comment]
Sorry I wasn't clear. How did you install those packages? Pip, conda, from source?

Anyway, I don't think it's worth spending a whole lot of time dwelling on why things _work_ for you, I am glad they do! And I do think we've concluded that the problem lies in a conflict between the OSX version the package is compiled with, and the OSX version on which it is installed. PIP doesn't have that problem.

**Comment by pgkirsch** [comment]
Ah my bad. I usually install using pip, but for the system python stuff I installed from source.

I'm not sure I understand your conclusion because installing using my anaconda instance of python still does not work using either pip or source to install. This matters because the package I am using cvxopt for is installed as an anaconda package. Happy to close this ticket though, because this seems to be an anaconda issue rather than a cvxopt issue.

**Comment by EmmanuelBoidot** [comment]
I ran into this issue today. I'm using mostly Anaconda python and it wasn't working at first. However after installing everything for factory Python (using pip install), I don't get the library error anymore, even when using Anaconda Python. I guess that's an ok fix for most people...
I did not try the conda install cvxopt though, so I can't comment on that part.
