### ISSUE TITLE
windows - how to install - thx

### ISSUE THREAD

**Issue by drandreaskrueger** [cvxopt/cvxopt#67]
```
git clone https://github.com/cvxopt/cvxopt.git
cd cvxopt
python setup.py install
```

results in:

```
running install
running bdist_egg
running egg_info
writing cvxopt.egg-info\PKG-INFO
writing top-level names to cvxopt.egg-info\top_level.txt
writing dependency_links to cvxopt.egg-info\dependency_links.txt
writing pbr to cvxopt.egg-info\pbr.json
reading manifest file 'cvxopt.egg-info\SOURCES.txt'
writing manifest file 'cvxopt.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'base' extension
cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda\include -IC:\Anaconda\PC /Tcsrc/C/base.c /Fobuild\temp.win-amd
64-2.7\Release\src/C/base.obj
error: command 'cl.exe' failed: No such file or directory
```

also see https://github.com/pystruct/pystruct/issues/190

Please help, thanks.

**Comment by drandreaskrueger** [comment]
please publish a binary.

Or, ideally, a working:

    pip install cvxopt

I would love to do all this on a real operating system, but that stupid workplace is forcing us to use Windows.

**Comment by drandreaskrueger** [comment]
P.S.: I have also tried [anaconda like described in the manual](http://pystruct.github.io/installation.html#alternative-anaconda)

    conda install cvxopt

but that results in

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Package missing in current win-64 channels:
  - cvxopt

You can search for packages on anaconda.org with

    anaconda search -t conda cvxopt
```

**Comment by drandreaskrueger** [comment]
because it is actually wrong. This one works:

    conda install -c omnia cvxopt

Then ... continue:

```
SET VS90COMNTOOLS=%VS100COMNTOOLS%
SET DISTUTILS_USE_SDK=1
SET MSSdk=1
pip install cvxpy
```

results in:

```
C:\Users\Andreas>pip install cvxpy
Collecting cvxpy
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9 in c:\anaconda\lib\site-packages (from cvxpy)
Requirement already satisfied (use --upgrade to upgrade): multiprocess in c:\anaconda\lib\site-packages (from cvxpy)
Collecting scs>=1.1.3 (from cvxpy)
  Using cached scs-1.2.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): fastcache in c:\anaconda\lib\site-packages (from cvxpy)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.15 in c:\anaconda\lib\site-packages (from cvxpy)
Requirement already satisfied (use --upgrade to upgrade): six in c:\anaconda\lib\site-packages (from cvxpy)
Requirement already satisfied (use --upgrade to upgrade): toolz in c:\anaconda\lib\site-packages (from cvxpy)
Requirement already satisfied (use --upgrade to upgrade): ecos>=2 in c:\anaconda\lib\site-packages (from cvxpy)
Collecting CVXcanon>=0.0.22 (from cvxpy)
  Using cached CVXcanon-0.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): dill>=0.2.5 in c:\anaconda\lib\site-packages (from multiproces
s->cvxpy)
Requirement already satisfied (use --upgrade to upgrade): pyreadline>=1.7.1 in c:\anaconda\lib\site-packages (from dill>
=0.2.5->multiprocess->cvxpy)
Building wheels for collected packages: scs, CVXcanon
  Running setup.py bdist_wheel for scs ... done
  Running setup.py clean for scs
  Running setup.py bdist_wheel for CVXcanon ... error
  Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\andreas\\a
ppdata\\local\\temp\\pip-build-trzixt\\CVXcanon\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read()
.replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\andreas\appdata\local\temp\tmpsqutzdpip-wheel- --pyt
hon-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  copying src\python\canonInterface.py -> build\lib.win-amd64-2.7
  copying src\python\CVXcanon.py -> build\lib.win-amd64-2.7
  copying src\python\_version__.py -> build\lib.win-amd64-2.7
  running build_ext
  building '_CVXcanon' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\src\python
  cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc/ -Isrc/python/ -Iinclude/Eigen -IC:\Anaconda\lib\site-packages\numpy
\core\include -IC:\Anaconda\include -IC:\Anaconda\PC /Tpsrc/CVXcanon.cpp /Fobuild\temp.win-amd64-2.7\Release\src/CVXcano
n.obj
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for CVXcanon
  Running setup.py clean for CVXcanon
Failed to build scs CVXcanon
```

**Comment by drandreaskrueger** [comment]
[About the first approach at the top](https://github.com/cvxopt/cvxopt/issues/67#issue-172028186) and the

    cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda\include -IC:\Anaconda\PC /Tcsrc/C/base.c /Fobuild\temp.win-amd64-2.7\Release\src/C/base.obj
    error: command 'cl.exe' failed: No such file or directory



I have checked 
* `\cvxopt\src\C` and YES, there is a `base.c` 
* `C:\Anaconda` and YES, there is a folder `include`
* `C:\Anaconda` and NO, there is no folder `PC`
* `\cvxopt\build\temp.win-amd64-2.7\Release\src\C` and NO, there is no `base.obj`

Hypothesis: it should perhaps NOT say 

    cl.exe ... /Fobuild\temp.win-amd64-2.7\Release\src/C/base.obj

but rather

    cl.exe ... /Fobuild\temp.win-amd64-2.7\Release\src\C\base.obj

?
Then your installation script has a bug!

**Comment by drandreaskrueger** [comment]
different attempt:

uninstalled VCForPython27.msi
installed VCForPython27.msi

    pip install "setuptools>=6.0"
    pip install CVXcanon

similar result

```
    ....
  creating build\temp.win-amd64-2.7\Release\src\python
  cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc/ -Isrc/python/ -Iinclude/Eigen -IC:\Anaconda\lib\site-packages\numpy
\core\include -IC:\Anaconda\include -IC:\Anaconda\PC /Tpsrc/CVXcanon.cpp /Fobuild\temp.win-amd64-2.7\Release\src/CVXcano
n.obj
  error: command 'cl.exe' failed: No such file or directory
```

**Comment by drandreaskrueger** [comment]
another route tried, get whl files from: http://www.lfd.uci.edu/~gohlke/pythonlibs/#cvxopt and then

    pip install cvxopt-1.1.7-cp27-none-win_amd64.whl --use-wheel
    pip install cvxpy-0.4.3-py2-none-any.whl --use-wheel

and now:

     nosetests cvxpy

results in:

```
C:\Users\Andreas\installscheisse>nosetests cvxpy
E
======================================================================
ERROR: Failure: ImportError (No module named _multiprocess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\nose\loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\Anaconda\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "C:\Anaconda\lib\site-packages\cvxpy\__init__.py", line 25, in <module>
    from cvxpy.problems.problem import Problem
  File "C:\Anaconda\lib\site-packages\cvxpy\problems\problem.py", line 36, in <module>
    import multiprocess as multiprocessing
  File "C:\Anaconda\lib\site-packages\multiprocess\__init__.py", line 84, in <module>
    import _multiprocess as _multiprocessing
ImportError: No module named _multiprocess

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

**Comment by drandreaskrueger** [comment]
git clone https://github.com/uqfoundation/multiprocess.git
    cd multiprocess
    python setup.py install

**Comment by martinandersen** [comment]
Please see the updated the [installation instructions for Windows](http://cvxopt.org/install/index.html#windows).
