### ISSUE TITLE
solver.qp error message not helpful

### ISSUE THREAD

**Issue by forcecore** [cvxopt/cvxopt#95]
Hi, I'm unsure how to get around this error

sol = solvers.qp(P, q, G, h, A, b)
ValueError: Rank(A) < p or Rank([P; A; G]) < n

When np.linalg.matrix_rank results are as follows:
rnk P:
1846
rnk q:
0
rnk G:
0
rnk h:
0
rnk A:
308
rnk b:
1

I guess, maybe "n
 is length of unknowns (x)? My len(x) is of 2008. I'm unsure what "p" is.

```
Traceback (most recent call last):
  File "/home/forcecore/usr/venv/lib/python3.5/site-packages/cvxopt/coneprog.py", line 2065, in coneqp
    try: f = kktsolver(W)
  File "/home/forcecore/usr/venv/lib/python3.5/site-packages/cvxopt/coneprog.py", line 1981, in kktsolver
    return factor(W, P)
  File "/home/forcecore/usr/venv/lib/python3.5/site-packages/cvxopt/misc.py", line 1472, in factor
    lapack.potrf(F['K'])
ArithmeticError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./iscas.py", line 888, in <module>
    g = run_tfplacer( "s13207" )
  File "./iscas.py", line 876, in run_tfplacer
    tfp.run()
  File "/home/forcecore/work/placer/tfplacer.py", line 512, in run
    self.place_cells()
  File "/home/forcecore/work/placer/tfplacer.py", line 483, in place_cells
    xy = calc_xy_init(g) # initial pos, in a tensor
  File "/home/forcecore/work/placer/tfplacer.py", line 157, in calc_xy_init
    sol = solvers.qp(P, q, G, h, A, b)
  File "/home/forcecore/usr/venv/lib/python3.5/site-packages/cvxopt/coneprog.py", line 4470, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "/home/forcecore/usr/venv/lib/python3.5/site-packages/cvxopt/coneprog.py", line 2067, in coneqp
    raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
ValueError: Rank(A) < p or Rank([P; A; G]) < n
```

**Comment by martinandersen** [comment]
The error message refers to the [documentation](http://cvxopt.org/userguide/coneprog.html#quadratic-cone-programs): 

> It is required that the problem is solvable and that
>
>    Rank(A) = p,   rank([P; G; A]) = n
>
> where p is the number or rows of A and n is the number of columns of G and A. 

Roughly speaking, you have redundant constraints if your problem does not satisfy this condition.

**Comment by forcecore** [comment]
It did, thank you!
